name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/FE.yml'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      WINDOWS_DEPLOY_PATH: 'C:\\inetpub\\wwwroot\\dev.imraninnovations'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.20.0'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build the project
        run: |
          cd client
          npm run build

      - name: Create deployment archive
        run: |
          cd client
          zip -r frontend-dist.zip dist/

      - name: Copy deployment archive to Server under dist folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: "client/frontend-dist.zip"
          target: "${{ env.WINDOWS_DEPLOY_PATH }}\\dist\\frontend-dist.zip"

      - name: Deploy Frontend and Restart IIS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          shell: powershell
          script: |
            powershell.exe -Command "
                # Set paths for zip and extraction
                $zipPath = 'C:\\inetpub\\wwwroot\\dev.imraninnovations\\dist\\frontend-dist.zip'
                $webRootPath = 'C:\\inetpub\\wwwroot\\dev.imraninnovations\\dist'

                # Check if the zip file exists
                if (Test-Path -Path $zipPath) {
                    Expand-Archive -Path $zipPath -DestinationPath $webRootPath -Force;
                    Remove-Item -Path $zipPath -Force;
                }
